//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;

    public partial class StudentTB
    {
        public int sid { get; set; }
        public string fullname { get; set; }
        public string school { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string address { get; set; }
        public string grade { get; set; }
        public string gender { get; set; }
        public string subject { get; set; }
        public string tpnum { get; set; }
        public string parentname { get; set; }
        public string parenttpnum { get; set; }
        public string imagepath { get; set; }

        public string LoginErrorMessage{get;set;}
    }
}
